### PR TITLE
Public data system vendor inventory details

### PR DESCRIPTION
**Pull request by traviskorte**
First pass at a writeup of the inventory dataset.

### CODE REVIEW

**Comment by joelrip** [comment]
Good. Will we have a direct link to the tables of data that these
paragraphs are based on? I think that would be useful.

**Comment by traviskorte** [comment]
I don't know how best to do that technically, but I agree it would be nice
to have the table. Ash, how do you like to do images in GitHub pages?

**Comment by roughani** [comment]
I'm not sure where the question of images came from, but feel free to send them to me and I can make sure they end up in the doc.

We have many options with the tables:
- "Publish to Web" from Google Spreadsheet and link to URL
- Export as CSV and drop into GitHub ([example](https://github.com/roughani/csv/blob/master/all_050_in_06.P1.csv))
- Convert into HTML ([example](http://derekeder.github.io/csv-to-html-table/))

**Comment by traviskorte** [comment]
Not sure why I said "images," definitely meant tables. I'll do option #2.
Thanks.

**Comment by traviskorte** [comment]
I don't have push access to the repo, but here is the CSV to upload.

**Pull request merged**
